#!/usr/bin/env python3
"""Synchronise generated content in the FezaPlugin monorepo.

Single sources of truth:
  * shared/*.md                       -> copied into every skill's references/
  * shared/packages/<pkg>/*.md        -> copied into every skill of package <pkg> only
                                         (or only the skills listed in PACKAGE_SHARED_SCOPE)
  * CROSS_SKILL_REFERENCES (below)    -> reference files one skill borrows from another
  * CROSS_SKILL_SCRIPTS (below)       -> tool scripts a skill runs from another skill
  * plugins/<pkg>/skills/<skill>/     -> mirrored flat into the root skills/ directory
  * VERSION                           -> "version" field of every versioned manifest
                                         and the version badge in README.md / README.tr.md

Usage:
  python scripts/sync.py           write all generated files
  python scripts/sync.py --check   report drift and exit 1 if anything is out of date

Only the Python standard library is used.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED_DIR = ROOT / "shared"
PACKAGE_SHARED_DIR = SHARED_DIR / "packages"
PLUGINS_DIR = ROOT / "plugins"
ROOT_SKILLS_DIR = ROOT / "skills"
VERSION_FILE = ROOT / "VERSION"

# Reference files that a skill reads from another skill. Skills must never point
# outside their own folder, so the file is copied into the consumer's references/.
# (source skill, file name, destination skill)
CROSS_SKILL_REFERENCES: list[tuple[str, str, str]] = [
    ("srs-generate", "well-formed-requirements.md", "srs-review"),
    ("srs-generate", "srs-outline-29148.md", "srs-review"),
    ("srs-generate", "language-guidelines.md", "srs-review"),
    ("srs-generate", "well-formed-requirements.md", "req-classify"),
    ("srs-generate", "language-guidelines.md", "req-classify"),
    ("srs-generate", "well-formed-requirements.md", "iso29148-req"),
    ("iso12207-audit", "12207-processes.md", "complaints-to-compliance"),
    ("hci-execute", "ux-writing.md", "heuristic-eval"),
    ("hci-execute", "ux-writing.md", "hci-review"),
]

# Tool scripts that a skill runs from another skill. Unlike references these copies
# carry no generated header (they are executed byte for byte), so drift is detected
# by content comparison and stale copies by the rule below.
# (source skill, file name, destination skill) -> <destination skill>/scripts/<file>
CROSS_SKILL_SCRIPTS: list[tuple[str, str, str]] = [
    ("hci-execute", "verify-ui.mjs", "heuristic-eval"),
    ("hci-execute", "verify-ui.mjs", "color-audit"),
    ("hci-execute", "verify-ui.mjs", "cognitive-load"),
    ("hci-execute", "verify-ui.mjs", "hci-review"),
    ("hci-execute", "contrast.py", "heuristic-eval"),
    ("hci-execute", "contrast.py", "color-audit"),
    ("hci-execute", "contrast.py", "cognitive-load"),
    ("hci-execute", "contrast.py", "hci-review"),
]

# Shared dependency files copied only into the listed skills instead of every skill
# of the package. Files absent from this map keep the package-wide behaviour.
PACKAGE_SHARED_SCOPE: dict[str, set[str]] = {
    "deceptive-patterns.md": {"heuristic-eval", "hci-review", "hci-execute"},
    "evidence-rubric.md": {"heuristic-eval", "hci-review", "color-audit", "cognitive-load"},
    "fix-mode.md": {"heuristic-eval", "color-audit", "cognitive-load", "hci-review"},
    "thresholds.md": {"hci-execute", "heuristic-eval", "color-audit", "cognitive-load", "hci-review"},
}

# Manifests whose top-level "version" field follows VERSION.
PLUGIN_MANIFEST_DIRS = (".claude-plugin", ".codex-plugin", ".cursor-plugin")
ROOT_VERSIONED_MANIFESTS = ("gemini-extension.json",)
VERSION_BADGE_FILES = ("README.md", "README.tr.md")

ROOT_SKILLS_README = """# Generated directory - do not edit

This directory is generated by `python scripts/sync.py` from
`plugins/<package>/skills/<skill>/`. It exists so that clients which expect a
single top-level `skills/` folder (Gemini CLI extensions, `npx skills`, other
Agent Skills clients) can discover every FezaPlugin skill.

Edit skills under `plugins/`, then run `python scripts/sync.py`.
"""


# Files that are never treated as skill sources or mirror content: byte-code caches
# and editor/OS droppings. These must be skipped everywhere a skill tree is walked,
# otherwise a stray __pycache__/*.pyc (e.g. produced by `python -m py_compile` in CI)
# would be reported as a missing or stale generated file.
IGNORED_PARTS = {"__pycache__", ".DS_Store"}
IGNORED_SUFFIXES = {".pyc", ".pyo"}


def is_ignored(path: Path) -> bool:
    """True when a path is a byte-code cache or OS/editor dropping to be skipped."""
    if path.suffix.lower() in IGNORED_SUFFIXES:
        return True
    return any(part in IGNORED_PARTS for part in path.parts)


def header(source: str) -> str:
    return f"<!-- generated from {source} — do not edit -->\n"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def skill_dirs() -> dict[str, Path]:
    """Map skill name -> skill directory under plugins/."""
    found: dict[str, Path] = {}
    for skill_md in sorted(PLUGINS_DIR.glob("*/skills/*/SKILL.md")):
        name = skill_md.parent.name
        if name in found:
            raise SystemExit(f"duplicate skill name across packages: {name}")
        found[name] = skill_md.parent
    return found


def is_generated(path: Path) -> bool:
    try:
        with path.open(encoding="utf-8") as fh:
            return fh.readline().startswith("<!-- generated from ")
    except (OSError, UnicodeDecodeError):
        return False


def _scope_skills(fname: str) -> set[str] | None:
    """Skills a package-shared file is restricted to, or None for package-wide."""
    scope = PACKAGE_SHARED_SCOPE.get(fname)
    if scope is None:
        return None
    return scope


def expected_plugin_files(skills: dict[str, Path]) -> dict[Path, str]:
    """Generated files that live inside plugins/."""
    out: dict[Path, str] = {}
    shared_files = sorted(SHARED_DIR.glob("*.md"))
    for skill_dir in skills.values():
        package = skill_dir.parent.parent.name
        package_files = sorted((PACKAGE_SHARED_DIR / package).glob("*.md"))
        for src in shared_files + package_files:
            scope = _scope_skills(src.name)
            if scope is not None and skill_dir.name not in scope:
                continue
            rel = src.relative_to(ROOT).as_posix()
            out[skill_dir / "references" / src.name] = header(rel) + read_text(src)
    packages = {d.parent.parent.name for d in skills.values()}
    for pkg_dir in sorted(PACKAGE_SHARED_DIR.glob("*")) if PACKAGE_SHARED_DIR.is_dir() else []:
        if pkg_dir.is_dir() and pkg_dir.name not in packages:
            raise SystemExit(f"package-scoped shared directory for unknown package: {pkg_dir.relative_to(ROOT)}")
    for fname, scope in PACKAGE_SHARED_SCOPE.items():
        unknown = scope - set(skills)
        if unknown:
            raise SystemExit(f"PACKAGE_SHARED_SCOPE[{fname!r}] lists unknown skill(s): {sorted(unknown)}")
    for src_skill, fname, dst_skill in CROSS_SKILL_REFERENCES:
        if src_skill not in skills or dst_skill not in skills:
            raise SystemExit(f"cross-skill reference uses unknown skill: {src_skill} -> {dst_skill}")
        src = skills[src_skill] / "references" / fname
        if not src.is_file():
            raise SystemExit(f"cross-skill reference source missing: {src.relative_to(ROOT)}")
        rel = src.relative_to(ROOT).as_posix()
        out[skills[dst_skill] / "references" / fname] = header(rel) + read_text(src)
    for src_skill, fname, dst_skill in CROSS_SKILL_SCRIPTS:
        if src_skill not in skills or dst_skill not in skills:
            raise SystemExit(f"cross-skill script uses unknown skill: {src_skill} -> {dst_skill}")
        src = skills[src_skill] / "scripts" / fname
        if not src.is_file():
            raise SystemExit(f"cross-skill script source missing: {src.relative_to(ROOT)}")
        out[skills[dst_skill] / "scripts" / fname] = read_text(src)
    return out


def stale_generated_files(skills: dict[str, Path], expected: dict[Path, str]) -> list[Path]:
    """Generated files in plugins/ that no longer have a source."""
    stale = []
    for skill_dir in skills.values():
        for f in sorted((skill_dir / "references").glob("*.md")):
            if f not in expected and is_generated(f):
                stale.append(f)
        # Script copies carry no header. A script is stale only when it has the name
        # of a cross-skill script and the skill is not its source, so hand-added
        # scripts are never removed by accident and source scripts are kept.
        sources = {fname: src for src, fname, _ in CROSS_SKILL_SCRIPTS}
        for f in sorted((skill_dir / "scripts").glob("*")):
            if is_ignored(f) or f in expected or f.name not in sources:
                continue
            if skill_dir == skills.get(sources[f.name]):
                continue
            stale.append(f)
    return stale


def version_updates(version: str) -> dict[Path, str]:
    out: dict[Path, str] = {}
    manifests = [p for d in PLUGIN_MANIFEST_DIRS for p in PLUGINS_DIR.glob(f"*/{d}/plugin.json")]
    manifests += [ROOT / m for m in ROOT_VERSIONED_MANIFESTS if (ROOT / m).is_file()]
    for path in sorted(manifests):
        data = json.loads(read_text(path))
        data["version"] = version
        out[path] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    # Static version badge in the READMEs.
    for name in VERSION_BADGE_FILES:
        path = ROOT / name
        if path.is_file():
            text = read_text(path)
            out[path] = re.sub(r"(img\.shields\.io/badge/version-)\d+\.\d+\.\d+(-)", rf"\g<1>{version}\g<2>", text)
    return out


def root_skill_tree(skills: dict[str, Path], plugin_files: dict[Path, str], stale: list[Path]) -> dict[Path, bytes]:
    """Expected content of the flat root skills/ mirror (after plugin files are synced)."""
    out: dict[Path, bytes] = {ROOT_SKILLS_DIR / "README.md": ROOT_SKILLS_README.encode("utf-8")}
    for name, skill_dir in skills.items():
        files = {p for p in skill_dir.rglob("*") if p.is_file() and not is_ignored(p)} | {
            p for p in plugin_files if p.is_relative_to(skill_dir)
        }
        for f in sorted(files - set(stale)):
            if f in plugin_files:
                data = plugin_files[f].encode("utf-8")
            else:
                data = f.read_bytes().replace(b"\r\n", b"\n")
            out[ROOT_SKILLS_DIR / name / f.relative_to(skill_dir)] = data
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="report drift without writing; exit 1 on drift")
    args = parser.parse_args()

    version = read_text(VERSION_FILE).strip()
    skills = skill_dirs()
    plugin_files = expected_plugin_files(skills)
    stale = stale_generated_files(skills, plugin_files)
    manifests = version_updates(version)
    mirror = root_skill_tree(skills, plugin_files, stale)

    expected: dict[Path, bytes] = {p: t.encode("utf-8") for p, t in plugin_files.items()}
    expected.update({p: t.encode("utf-8") for p, t in manifests.items()})
    expected.update(mirror)

    drift: list[str] = []
    for path, data in sorted(expected.items()):
        current = path.read_bytes().replace(b"\r\n", b"\n") if path.is_file() else None
        if current != data:
            drift.append(("update " if current is not None else "create ") + path.relative_to(ROOT).as_posix())
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)

    removals = list(stale)
    if ROOT_SKILLS_DIR.is_dir():
        removals += [p for p in ROOT_SKILLS_DIR.rglob("*") if p.is_file() and not is_ignored(p) and p not in mirror]
    for path in sorted(set(removals)):
        drift.append("remove " + path.relative_to(ROOT).as_posix())
        if not args.check:
            path.unlink()
    if not args.check and ROOT_SKILLS_DIR.is_dir():
        for d in sorted((p for p in ROOT_SKILLS_DIR.rglob("*") if p.is_dir() and not is_ignored(p)), reverse=True):
            if not any(d.iterdir()):
                shutil.rmtree(d)

    summary = (
        f"{len(skills)} skills, {len(plugin_files)} generated reference files, "
        f"{len(manifests)} version-tracked files (version {version}), {len(mirror)} mirrored files"
    )
    if args.check:
        if drift:
            print("sync --check: drift detected")
            for line in drift:
                print("  " + line)
            print("Run: python scripts/sync.py")
            return 1
        print(f"sync --check: OK ({summary})")
        return 0
    print(f"sync: {len(drift)} change(s) written ({summary})")
    for line in drift[:50]:
        print("  " + line)
    if len(drift) > 50:
        print(f"  ... {len(drift) - 50} more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
